services:
  traefik:
    container_name: tp1_traefik
    image: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 2222:2222
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
     - traefik.enable=false

  gitea:
    container_name: tp1_gitea
    ports:
      - "3000:3000"
      - "222:2222"
    image: gitea/gitea:latest-rootless
    command: 
     # - gitea admin user create --username=test --password=test --email=test@xx.com --admin --config=/etc/gitea/app.ini
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: database:3306
      GITEA__database__NAME: ${GITEA_DB_NAME}
      GITEA__database__USER: ${GITEA_ADMIN}
      GITEA__database__PASSWD: /run/secrets/gitea_db_passwd
      GITEA__server__ROOT_URL: https://${GITEA_HOSTNAME_ENV}
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    depends_on:
      - database
    secrets:
      - gitea_db_passwd
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${GITEA_HOSTNAME_ENV}`)
      - traefik.http.routers.gitea.tls=true
      #only in production
      #- traefik.http.routers.gitea.tls.certresolver=letsencrypt
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=2222
      

  database:
    container_name: tp1_gitea_db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/gitea_db_root_passwd
      MYSQL_USER: ${GITEA_ADMIN}
      MYSQL_PASSWORD: /run/secrets/gitea_db_passwd
      MYSQL_DATABASE: ${GITEA_DB_NAME}
    secrets:
      - gitea_db_root_passwd
      - gitea_db_passwd
    volumes:
      - database-data:/var/lib/mysql
    labels:
      - traefik.enable=false

  runner1:
    container_name: gitea-runner-1
    image: gitea/act_runner
    restart: unless-stopped
    env_file:
      - ./gitea/.env.runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea  
    labels:
      - traefik.enable=false

  runner2:
    container_name: gitea-runner-2
    image: gitea/act_runner
    restart: unless-stopped
    env_file:
      - ./gitea/.env.runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea  
    labels:
      - traefik.enable=false

  runner3:
    container_name: gitea-runner-3
    image: gitea/act_runner
    restart: unless-stopped
    env_file:
      - ./gitea/.env.runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea  
    labels:
      - traefik.enable=false   

volumes:
  gitea-data:
  gitea-config:
  database-data:


secrets:
  gitea_db_passwd:
    file: ./gitea/.secrets.db_passwd
  gitea_db_root_passwd:
    file: ./gitea/.secrets.db_root_passwd

